### ISSUE TITLE
Download via Right-Click and "Save Link As" creates corrupt file

### ISSUE THREAD

**Issue by metmajer** [kelapure/microservices#1]
Hi @kelapure and thanks for sharing your vast knowledge on this interesting subject. I noticed however, that downloading the .pdf via Right-Click and "Save Link As" doesn't create the desired outcome. I suggest you create a release and append the .pdf file there. Should work!

**Comment by kelapure** [comment]
Done. Take a look now... https://github.com/kelapure/microservices/releases/tag/1.0

I intend to update the book and release it as a series of chapters on [cloud.rohitkelapure.com](cloud.rohitkelapure.com)

**Comment by metmajer** [comment]
@kelapure that helped! I'll follow your blog closely. We may find some touch points here or there.

PS: the link to your blog currently doesn't work. You've got to prepend a http:// to break out of github.com.
